name: Clean up lamp to Local Machine

on:
  #push:
  #  branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform init
        run: |
          terraform init
          
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-file
          
      - name: Terraform destroy
        run: terraform destroy -auto-approve tfplan

      #- name: Remove images
      #  run: docker rmi $(docker images --filter "reference=lamp-*" -q)
      
